# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0003_remove_lesson_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lesson', to='lesson.Lesson')),
            ],
        ),
    ]
