# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20170224_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='group',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='group.Group'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lesson',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson', to='lesson.Lesson'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='room',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='room.Room'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='user.User'),
        ),
    ]
