# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_lecture_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='date',
            new_name='date_time',
        ),
    ]
