# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-11 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='desription',
            new_name='description',
        ),
    ]
