# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_remove_lesson_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='timeout',
        ),
    ]
