# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
