# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20170206_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=620),
        ),
    ]
