# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-06 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20170206_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.BooleanField(),
        ),
    ]
