# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-06 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20170206_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='captain',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to='user.User'),
        ),
    ]
