# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_group_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='img',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
